# Generated by Django 2.2.5 on 2020-01-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('birthday', models.DateField()),
                ('size', models.IntegerField(default=0)),
                ('heel', models.IntegerField(default=0)),
                ('fvbr', models.CharField(max_length=100)),
                ('fvshbr', models.CharField(max_length=100)),
                ('fvclbr', models.CharField(max_length=100)),
                ('zodata', models.CharField(max_length=100)),
                ('appdata', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('ofadd', models.CharField(max_length=100)),
                ('ofty', models.CharField(max_length=100)),
                ('posi', models.CharField(max_length=100)),
                ('out', models.CharField(max_length=100)),
                ('pur', models.CharField(max_length=100)),
                ('situ', models.CharField(max_length=100)),
            ],
        ),
    ]
